stages:
  - scan
  - build
  - update-dependencies

osv-scanner:
  stage: scan
  image: golang:latest
  script:
    - go install github.com/google/osv-scanner/cmd/osv-scanner@v1
    - osv-scanner -r .

publish:
  image: gradle:jdk17
  stage: build
  only:
    - main
  except:
    - schedules
  variables:
    USERNAME: $NEXUS_USER
    PASSWORD: $NEXUS_PWD
  script:
    - ./gradlew publish

build:
  image: gradle:jdk17
  stage: build
  except:
    - schedules
  variables:
    USERNAME: $NEXUS_USER
    PASSWORD: $NEXUS_PWD
  script:
    - ./gradlew build

renovate:
  image: renovate/renovate
  stage: update-dependencies
  only:
    - schedules
  script:
    - renovate --platform gitlab --token $RENOVATE_TOKEN $CI_PROJECT_PATH
