name: Build and Deploy

on:
    push:
        branches: [ '**' ]

jobs:
    build:
        runs-on: self-hosted
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3
            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: 17
                    distribution: zulu
            -   name: Build with Gradle
                run: |
                    chmod 777 gradlew
                    ./gradlew build
                env:
                    NEXUS_USER: ${{ secrets.NEXUS_USER }}
                    NEXUS_PWD: ${{ secrets.NEXUS_PWD }}

    publish:
        runs-on: self-hosted
        if: github.ref == 'refs/heads/main'
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3
            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: 17
                    distribution: zulu
            -   name: Publish to Nexus
                run: |
                    chmod 777 gradlew
                    ./gradlew publish
                env:
                    NEXUS_USER: ${{ secrets.NEXUS_USER }}
                    NEXUS_PWD: ${{ secrets.NEXUS_PWD }}
